//! HTML report rendering with inline CSS.
//!
//! Generates self-contained HTML reports suitable for
//! audit submission without external dependencies.

use super::*;

const CSS: &str = r#"
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
       margin: 40px auto; max-width: 960px; color: #1a1a2e; background: #f8f9fa; }
h1 { color: #1a1a2e; border-bottom: 3px solid #1a73e8; padding-bottom: 8px; }
h2 { color: #333; margin-top: 30px; }
table { width: 100%; border-collapse: collapse; margin: 15px 0;
        background: white; border-radius: 6px; overflow: hidden;
        box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
th, td { padding: 10px 14px; text-align: left; border-bottom: 1px solid #e0e0e0; }
th { background: #263238; color: white; font-weight: 600; }
tr:hover { background: #f5f5f5; }
.pass { color: #2e7d32; font-weight: bold; }
.fail { color: #c62828; font-weight: bold; }
.warn { color: #f57f17; font-weight: bold; }
.status-pass { background: #e8f5e9; }
.status-fail { background: #ffebee; }
.status-warn { background: #fff8e1; }
.badge { display: inline-block; padding: 3px 10px; border-radius: 12px;
         font-size: 12px; font-weight: 600; }
.badge-pass { background: #c8e6c9; color: #2e7d32; }
.badge-fail { background: #ffcdd2; color: #c62828; }
.badge-warn { background: #ffecb3; color: #f57f17; }
.summary-box { display: flex; gap: 20px; margin: 20px 0; }
.summary-card { flex: 1; padding: 20px; border-radius: 8px; text-align: center; }
.summary-card h3 { margin: 0 0 8px 0; font-size: 14px; color: #666; text-transform: uppercase; }
.summary-card .value { font-size: 32px; font-weight: bold; }
.meta { color: #666; font-size: 13px; margin-bottom: 20px; }
.footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #e0e0e0;
          color: #999; font-size: 12px; text-align: center; }
.section { margin: 25px 0; }
"#;

/// Trait for types that can be rendered as HTML report
pub trait HtmlReport {
    fn to_html(&self) -> String;
}

fn status_badge(status: RuleStatus) -> String {
    let class = status.css_class();
    format!(r#"<span class="badge-{}">{}</span>"#, class, status)
}

fn status_cell(status: RuleStatus) -> String {
    let class = status.css_class();
    format!(r#"<td class="status-{}">{}</td>"#, class, status)
}

fn html_page(title: &str, body: String) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="zh-CN">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><style>{css}</style></head>
<body>
{body}
<div class="footer">Generated by kms-cli | DJCP Level 3 Compliance Reporting</div>
</body></html>"#,
        css = CSS,
    )
}

pub fn render_crypto_report(report: &CryptoConfigReport) -> String {
    let mut body = String::new();

    // Title
    body.push_str(&format!(
        "<h1>{} Crypto Configuration Report</h1>\
         <div class=\"meta\">Generated: {} | Server: {}</div>",
        "KMS", report.report.generated_at, report.report.scope.server
    ));

    // Summary cards
    body.push_str("<div class=\"summary-box\">");
    body.push_str(&summary_card(
        "Total Keys",
        &report.summary.total_keys.to_string(),
        "#1a73e8",
    ));
    let active = report
        .summary
        .by_status
        .iter()
        .find(|s| s.status == "Active" || s.status == "active")
        .map(|s| s.count)
        .unwrap_or(0);
    body.push_str(&summary_card("Active Keys", &active.to_string(), "#2e7d32"));
    let algorithms = report.summary.by_algorithm.len();
    body.push_str(&summary_card(
        "Algorithms",
        &algorithms.to_string(),
        "#f57f17",
    ));
    body.push_str(&summary_card(
        "Compliance",
        &format!("{}", report.compliance.overall),
        "#c62828",
    ));
    body.push_str("</div>");

    // Compliance status
    body.push_str("<h2>Compliance Status</h2>");
    body.push_str(&render_compliance_table(&report.compliance.rules));

    // Algorithm distribution
    body.push_str("<h2>Algorithm Distribution</h2>");
    body.push_str("<table><tr><th>Algorithm</th><th>Count</th><th>%</th></tr>");
    for a in &report.summary.by_algorithm {
        let pct = if report.summary.total_keys > 0 {
            (a.count as f64 / report.summary.total_keys as f64) * 100.0
        } else {
            0.0
        };
        body.push_str(&format!(
            "<tr><td>{}</td><td>{}</td><td>{:.1}%</td></tr>",
            a.algorithm, a.count, pct
        ));
    }
    body.push_str("</table>");

    // Key status distribution
    body.push_str("<h2>Key Status Distribution</h2>");
    body.push_str("<table><tr><th>Status</th><th>Count</th></tr>");
    for s in &report.summary.by_status {
        body.push_str(&format!(
            "<tr><td>{}</td><td>{}</td></tr>",
            s.status, s.count
        ));
    }
    body.push_str("</table>");

    // Key inventory
    body.push_str("<h2>Key Inventory</h2>");
    body.push_str(
        "<table><tr><th>Name</th><th>ID</th><th>Algorithm</th><th>Status</th><th>Tenant</th></tr>",
    );
    for k in &report.keys {
        body.push_str(&format!(
            "<tr><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            k.name,
            &k.key_id[..k.key_id.len().min(12)],
            k.spec,
            k.status,
            k.tenant_id
        ));
    }
    body.push_str("</table>");

    // Drift findings
    body.push_str("<h2>Drift Detection</h2>");
    if report.drift.detected {
        body.push_str("<table><tr><th>Severity</th><th>Description</th></tr>");
        for f in &report.drift.findings {
            body.push_str(&format!(
                "<tr><td>{}</td><td>{}</td></tr>",
                f.severity, f.description
            ));
        }
        body.push_str("</table>");
    } else {
        body.push_str("<p>No configuration drift detected.</p>");
    }

    html_page("Crypto Configuration Report", body)
}

pub fn render_compliance_report(report: &ComplianceReport) -> String {
    let mut body = String::new();

    body.push_str(&format!(
        "<h1>{} DJCP Self-Assessment Report</h1>\
         <div class=\"meta\">Generated: {} | Standard: {} | Server: {}</div>",
        "KMS", report.report.generated_at, report.standard, report.report.scope.server
    ));

    // Summary cards
    body.push_str("<div class=\"summary-box\">");
    body.push_str(&summary_card(
        "Total Controls",
        &report.summary.total_controls.to_string(),
        "#1a73e8",
    ));
    body.push_str(&summary_card(
        "Passed",
        &report.summary.passed.to_string(),
        "#2e7d32",
    ));
    body.push_str(&summary_card(
        "Failed",
        &report.summary.failed.to_string(),
        "#c62828",
    ));
    body.push_str(&summary_card(
        "Pass Rate",
        &format!("{:.0}%", report.summary.pass_rate_pct),
        "#f57f17",
    ));
    body.push_str("</div>");

    // Overall result
    body.push_str(&format!(
        "<p><strong>Overall Result:</strong> {}</p>",
        status_badge(report.overall_result)
    ));

    // Controls table
    body.push_str("<h2>Control Assessment</h2>");
    body.push_str("<table><tr><th>ID</th><th>Category</th><th>Requirement</th><th>Standard</th><th>Status</th></tr>");
    for c in &report.controls {
        body.push_str(&format!(
            "<tr class=\"status-{}\"><td>{}</td><td>{}</td><td>{}</td><td>{}</td><td>{}</td></tr>",
            c.status.css_class(),
            c.id,
            c.category,
            c.requirement,
            c.standard_ref,
            status_badge(c.status)
        ));
    }
    body.push_str("</table>");

    // Evidence details
    body.push_str("<h2>Evidence Details</h2>");
    body.push_str("<table><tr><th>ID</th><th>Evidence</th></tr>");
    for c in &report.controls {
        body.push_str(&format!(
            "<tr><td>{}</td><td>{}</td></tr>",
            c.id, c.evidence
        ));
    }
    body.push_str("</table>");

    html_page("DJCP Self-Assessment Report", body)
}

fn summary_card(title: &str, value: &str, color: &str) -> String {
    format!(
        r#"<div class="summary-card" style="border: 2px solid {color}; background: white;">
            <h3>{title}</h3>
            <div class="value" style="color: {color};">{value}</div>
        </div>"#,
    )
}

fn render_compliance_table(rules: &[ComplianceRuleResult]) -> String {
    let mut html = String::from(
        "<table><tr><th>Rule ID</th><th>Category</th><th>Requirement</th><th>Status</th></tr>",
    );
    for r in rules {
        html.push_str(&format!(
            "<tr class=\"status-{}\"><td>{}</td><td>{}</td><td>{}</td>{}</tr>",
            r.status.css_class(),
            r.id,
            r.category,
            r.requirement,
            status_cell(r.status)
        ));
    }
    html.push_str("</table>");
    html
}
